// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package core

import (
	"context"
	"net/http"

	mock "github.com/stretchr/testify/mock"
)

// NewMockHandler creates a new instance of MockHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHandler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHandler {
	mock := &MockHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHandler is an autogenerated mock type for the Handler type
type MockHandler struct {
	mock.Mock
}

type MockHandler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHandler) EXPECT() *MockHandler_Expecter {
	return &MockHandler_Expecter{mock: &_m.Mock}
}

// DownloadAttachment provides a mock function for the type MockHandler
func (_mock *MockHandler) DownloadAttachment(responseWriter http.ResponseWriter, request *http.Request) {
	_mock.Called(responseWriter, request)
	return
}

// MockHandler_DownloadAttachment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DownloadAttachment'
type MockHandler_DownloadAttachment_Call struct {
	*mock.Call
}

// DownloadAttachment is a helper method to define mock.On call
//   - responseWriter http.ResponseWriter
//   - request *http.Request
func (_e *MockHandler_Expecter) DownloadAttachment(responseWriter interface{}, request interface{}) *MockHandler_DownloadAttachment_Call {
	return &MockHandler_DownloadAttachment_Call{Call: _e.mock.On("DownloadAttachment", responseWriter, request)}
}

func (_c *MockHandler_DownloadAttachment_Call) Run(run func(responseWriter http.ResponseWriter, request *http.Request)) *MockHandler_DownloadAttachment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_DownloadAttachment_Call) Return() *MockHandler_DownloadAttachment_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHandler_DownloadAttachment_Call) RunAndReturn(run func(responseWriter http.ResponseWriter, request *http.Request)) *MockHandler_DownloadAttachment_Call {
	_c.Run(run)
	return _c
}

// GetPlayer provides a mock function for the type MockHandler
func (_mock *MockHandler) GetPlayer(responseWriter http.ResponseWriter, request *http.Request) {
	_mock.Called(responseWriter, request)
	return
}

// MockHandler_GetPlayer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPlayer'
type MockHandler_GetPlayer_Call struct {
	*mock.Call
}

// GetPlayer is a helper method to define mock.On call
//   - responseWriter http.ResponseWriter
//   - request *http.Request
func (_e *MockHandler_Expecter) GetPlayer(responseWriter interface{}, request interface{}) *MockHandler_GetPlayer_Call {
	return &MockHandler_GetPlayer_Call{Call: _e.mock.On("GetPlayer", responseWriter, request)}
}

func (_c *MockHandler_GetPlayer_Call) Run(run func(responseWriter http.ResponseWriter, request *http.Request)) *MockHandler_GetPlayer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_GetPlayer_Call) Return() *MockHandler_GetPlayer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHandler_GetPlayer_Call) RunAndReturn(run func(responseWriter http.ResponseWriter, request *http.Request)) *MockHandler_GetPlayer_Call {
	_c.Run(run)
	return _c
}

// Health provides a mock function for the type MockHandler
func (_mock *MockHandler) Health(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Health")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHandler_Health_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Health'
type MockHandler_Health_Call struct {
	*mock.Call
}

// Health is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockHandler_Expecter) Health(ctx interface{}) *MockHandler_Health_Call {
	return &MockHandler_Health_Call{Call: _e.mock.On("Health", ctx)}
}

func (_c *MockHandler_Health_Call) Run(run func(ctx context.Context)) *MockHandler_Health_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHandler_Health_Call) Return(err error) *MockHandler_Health_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHandler_Health_Call) RunAndReturn(run func(ctx context.Context) error) *MockHandler_Health_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function for the type MockHandler
func (_mock *MockHandler) Shutdown(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHandler_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type MockHandler_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockHandler_Expecter) Shutdown(ctx interface{}) *MockHandler_Shutdown_Call {
	return &MockHandler_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx)}
}

func (_c *MockHandler_Shutdown_Call) Run(run func(ctx context.Context)) *MockHandler_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockHandler_Shutdown_Call) Return(err error) *MockHandler_Shutdown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHandler_Shutdown_Call) RunAndReturn(run func(ctx context.Context) error) *MockHandler_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}

// UpdatePlayer provides a mock function for the type MockHandler
func (_mock *MockHandler) UpdatePlayer(responseWriter http.ResponseWriter, request *http.Request) {
	_mock.Called(responseWriter, request)
	return
}

// MockHandler_UpdatePlayer_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdatePlayer'
type MockHandler_UpdatePlayer_Call struct {
	*mock.Call
}

// UpdatePlayer is a helper method to define mock.On call
//   - responseWriter http.ResponseWriter
//   - request *http.Request
func (_e *MockHandler_Expecter) UpdatePlayer(responseWriter interface{}, request interface{}) *MockHandler_UpdatePlayer_Call {
	return &MockHandler_UpdatePlayer_Call{Call: _e.mock.On("UpdatePlayer", responseWriter, request)}
}

func (_c *MockHandler_UpdatePlayer_Call) Run(run func(responseWriter http.ResponseWriter, request *http.Request)) *MockHandler_UpdatePlayer_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_UpdatePlayer_Call) Return() *MockHandler_UpdatePlayer_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHandler_UpdatePlayer_Call) RunAndReturn(run func(responseWriter http.ResponseWriter, request *http.Request)) *MockHandler_UpdatePlayer_Call {
	_c.Run(run)
	return _c
}

// UploadAttachment provides a mock function for the type MockHandler
func (_mock *MockHandler) UploadAttachment(responseWriter http.ResponseWriter, request *http.Request) {
	_mock.Called(responseWriter, request)
	return
}

// MockHandler_UploadAttachment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadAttachment'
type MockHandler_UploadAttachment_Call struct {
	*mock.Call
}

// UploadAttachment is a helper method to define mock.On call
//   - responseWriter http.ResponseWriter
//   - request *http.Request
func (_e *MockHandler_Expecter) UploadAttachment(responseWriter interface{}, request interface{}) *MockHandler_UploadAttachment_Call {
	return &MockHandler_UploadAttachment_Call{Call: _e.mock.On("UploadAttachment", responseWriter, request)}
}

func (_c *MockHandler_UploadAttachment_Call) Run(run func(responseWriter http.ResponseWriter, request *http.Request)) *MockHandler_UploadAttachment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 http.ResponseWriter
		if args[0] != nil {
			arg0 = args[0].(http.ResponseWriter)
		}
		var arg1 *http.Request
		if args[1] != nil {
			arg1 = args[1].(*http.Request)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHandler_UploadAttachment_Call) Return() *MockHandler_UploadAttachment_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockHandler_UploadAttachment_Call) RunAndReturn(run func(responseWriter http.ResponseWriter, request *http.Request)) *MockHandler_UploadAttachment_Call {
	_c.Run(run)
	return _c
}

// newMockstore creates a new instance of mockstore. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockstore(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockstore {
	mock := &mockstore{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockstore is an autogenerated mock type for the store type
type mockstore struct {
	mock.Mock
}

type mockstore_Expecter struct {
	mock *mock.Mock
}

func (_m *mockstore) EXPECT() *mockstore_Expecter {
	return &mockstore_Expecter{mock: &_m.Mock}
}

// Download provides a mock function for the type mockstore
func (_mock *mockstore) Download(ctx context.Context, email string, uploadType string, filename string) (*Upload, error) {
	ret := _mock.Called(ctx, email, uploadType, filename)

	if len(ret) == 0 {
		panic("no return value specified for Download")
	}

	var r0 *Upload
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) (*Upload, error)); ok {
		return returnFunc(ctx, email, uploadType, filename)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, string) *Upload); ok {
		r0 = returnFunc(ctx, email, uploadType, filename)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*Upload)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, string) error); ok {
		r1 = returnFunc(ctx, email, uploadType, filename)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockstore_Download_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Download'
type mockstore_Download_Call struct {
	*mock.Call
}

// Download is a helper method to define mock.On call
//   - ctx context.Context
//   - email string
//   - uploadType string
//   - filename string
func (_e *mockstore_Expecter) Download(ctx interface{}, email interface{}, uploadType interface{}, filename interface{}) *mockstore_Download_Call {
	return &mockstore_Download_Call{Call: _e.mock.On("Download", ctx, email, uploadType, filename)}
}

func (_c *mockstore_Download_Call) Run(run func(ctx context.Context, email string, uploadType string, filename string)) *mockstore_Download_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *mockstore_Download_Call) Return(upload *Upload, err error) *mockstore_Download_Call {
	_c.Call.Return(upload, err)
	return _c
}

func (_c *mockstore_Download_Call) RunAndReturn(run func(ctx context.Context, email string, uploadType string, filename string) (*Upload, error)) *mockstore_Download_Call {
	_c.Call.Return(run)
	return _c
}

// Get provides a mock function for the type mockstore
func (_mock *mockstore) Get(ctx context.Context, field string, value string) (Player, error) {
	ret := _mock.Called(ctx, field, value)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 Player
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) (Player, error)); ok {
		return returnFunc(ctx, field, value)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string) Player); ok {
		r0 = returnFunc(ctx, field, value)
	} else {
		r0 = ret.Get(0).(Player)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string) error); ok {
		r1 = returnFunc(ctx, field, value)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// mockstore_Get_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Get'
type mockstore_Get_Call struct {
	*mock.Call
}

// Get is a helper method to define mock.On call
//   - ctx context.Context
//   - field string
//   - value string
func (_e *mockstore_Expecter) Get(ctx interface{}, field interface{}, value interface{}) *mockstore_Get_Call {
	return &mockstore_Get_Call{Call: _e.mock.On("Get", ctx, field, value)}
}

func (_c *mockstore_Get_Call) Run(run func(ctx context.Context, field string, value string)) *mockstore_Get_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockstore_Get_Call) Return(player Player, err error) *mockstore_Get_Call {
	_c.Call.Return(player, err)
	return _c
}

func (_c *mockstore_Get_Call) RunAndReturn(run func(ctx context.Context, field string, value string) (Player, error)) *mockstore_Get_Call {
	_c.Call.Return(run)
	return _c
}

// Health provides a mock function for the type mockstore
func (_mock *mockstore) Health(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Health")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockstore_Health_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Health'
type mockstore_Health_Call struct {
	*mock.Call
}

// Health is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockstore_Expecter) Health(ctx interface{}) *mockstore_Health_Call {
	return &mockstore_Health_Call{Call: _e.mock.On("Health", ctx)}
}

func (_c *mockstore_Health_Call) Run(run func(ctx context.Context)) *mockstore_Health_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockstore_Health_Call) Return(err error) *mockstore_Health_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockstore_Health_Call) RunAndReturn(run func(ctx context.Context) error) *mockstore_Health_Call {
	_c.Call.Return(run)
	return _c
}

// Shutdown provides a mock function for the type mockstore
func (_mock *mockstore) Shutdown(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Shutdown")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockstore_Shutdown_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Shutdown'
type mockstore_Shutdown_Call struct {
	*mock.Call
}

// Shutdown is a helper method to define mock.On call
//   - ctx context.Context
func (_e *mockstore_Expecter) Shutdown(ctx interface{}) *mockstore_Shutdown_Call {
	return &mockstore_Shutdown_Call{Call: _e.mock.On("Shutdown", ctx)}
}

func (_c *mockstore_Shutdown_Call) Run(run func(ctx context.Context)) *mockstore_Shutdown_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *mockstore_Shutdown_Call) Return(err error) *mockstore_Shutdown_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockstore_Shutdown_Call) RunAndReturn(run func(ctx context.Context) error) *mockstore_Shutdown_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type mockstore
func (_mock *mockstore) Update(ctx context.Context, p Player) error {
	ret := _mock.Called(ctx, p)

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, Player) error); ok {
		r0 = returnFunc(ctx, p)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockstore_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type mockstore_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - p Player
func (_e *mockstore_Expecter) Update(ctx interface{}, p interface{}) *mockstore_Update_Call {
	return &mockstore_Update_Call{Call: _e.mock.On("Update", ctx, p)}
}

func (_c *mockstore_Update_Call) Run(run func(ctx context.Context, p Player)) *mockstore_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 Player
		if args[1] != nil {
			arg1 = args[1].(Player)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockstore_Update_Call) Return(err error) *mockstore_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockstore_Update_Call) RunAndReturn(run func(ctx context.Context, p Player) error) *mockstore_Update_Call {
	_c.Call.Return(run)
	return _c
}

// Upload provides a mock function for the type mockstore
func (_mock *mockstore) Upload(ctx context.Context, upload *Upload) error {
	ret := _mock.Called(ctx, upload)

	if len(ret) == 0 {
		panic("no return value specified for Upload")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *Upload) error); ok {
		r0 = returnFunc(ctx, upload)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockstore_Upload_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upload'
type mockstore_Upload_Call struct {
	*mock.Call
}

// Upload is a helper method to define mock.On call
//   - ctx context.Context
//   - upload *Upload
func (_e *mockstore_Expecter) Upload(ctx interface{}, upload interface{}) *mockstore_Upload_Call {
	return &mockstore_Upload_Call{Call: _e.mock.On("Upload", ctx, upload)}
}

func (_c *mockstore_Upload_Call) Run(run func(ctx context.Context, upload *Upload)) *mockstore_Upload_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *Upload
		if args[1] != nil {
			arg1 = args[1].(*Upload)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *mockstore_Upload_Call) Return(err error) *mockstore_Upload_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockstore_Upload_Call) RunAndReturn(run func(ctx context.Context, upload *Upload) error) *mockstore_Upload_Call {
	_c.Call.Return(run)
	return _c
}
